### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by team-daniel** [DES-Lab/AALpy#51] opened 2023-09-25 09:40 UTC
Hi all! I am having an issue where 1 in every 4 or so runs of the `run_Alergia` function results in the error below. It seems to be random but I am not sure why it is doing this? 

![Screenshot from 2023-09-25 10-36-57](https://github.com/DES-Lab/AALpy/assets/55928249/b4a216cd-bebd-49fd-92d4-4da38b81e566)

**Comment by emuskardin** [comment] 2023-09-25 11:20
Hi,
this is something we observed when the underlying data looks like it has been generated with POMDP, instead of deterministically labeled MDP. However, it is quite hard to reproduce with randomly generated MDPs/POMDPs.

Could you provide the dataset with which we could reproduce a bug? (as csv, where O I O are separated by comma, and traces by new line)

**Comment by zwergziege** [comment] 2023-09-25 11:53
In the meantime you could try the development branch `statemerging-dev`. It has an implementation of Alergia that should not suffer from the same problem. If you check it out, you should be able to use 
```python
from aalpy.learning_algs.stochastic_passive.GeneralizedStateMerging import runAlergia
mdp = runAlergia(data, epsilon = 0.005) # or some other epsilon
```
to get an MDP. If you want a stochastic mealy machine instead, add the kw argument `output_behavior = "mealy"`, but be aware of the slight differences in the input formats (i.e. the initial output).

**Comment by emuskardin** [comment] 2023-09-27 11:09
I created a small script that is able to reproduce a bug in `alergia_dev_by_zero` branch in alergia_debug.py file.
I will attempt to find the cause of the bug.

**Comment by emuskardin** [comment] 2023-09-27 12:41
@team-daniel, should be fixed on the current master branch.

If you update with `pip install https://github.com/DES-Lab/AALpy/archive/master.zip` you should get no more errors.

**Closed by emuskardin** 2023-09-27 12:41 UTC
