### ISSUE TITLE
Running ALERGIA algorithm

### ISSUE THREAD

**Issue by pberko** [DES-Lab/AALpy#21] opened 2022-01-14 13:55 UTC
Hello,

I'm trying to learn the automaton:
![image](https://user-images.githubusercontent.com/86918539/149526099-d60fe87d-0c0a-4003-bd4e-5d827cc7efa6.png)
[https://github.com/pberko/al_rnn_results/blob/main/aut123.pdf](https://github.com/pberko/al_rnn_results/blob/main/aut123.pdf)

I did a random run on the automaton to get a prefix tree to prepare a trainig for learning and I got the file - 
[https://github.com/pberko/al_rnn_results/blob/main/train_100_123.csv](https://github.com/pberko/al_rnn_results/blob/main/train_100_123.csv)

Do you have an example how I can learn the original automaton from the training file using Alergia?

Thanks

**Comment by emuskardin** [comment] 2022-01-17 10:43
Hi,

input format for ALERGIA is discussed [at our Wiki](https://github.com/DES-Lab/AALpy/wiki/Passive-Learning-of-Stochastic-Automata), and examples on how to actually run ALERGIA can be found in our [examples file](https://github.com/DES-Lab/AALpy/blob/master/Examples.py).

As far as I understand you are trying to learn an MDP that conforms to the automata you presented. It is an MDP and not MC as you have outputs, that is True or False. For that, you need to provide inputs and outputs in the standard defined in our Wiki (link above). Basically a list of lists, where inner lists are Output x (Input, Ouput) sequances.

I do not get what are the label values in your CSV file.
In case of any confusion just take a look at Examples.py. There you will find functions that showcase MDP and MC learning with ALERGIA, and how to prepare the data for the algorithm.

All best,
Edi

**Comment by emuskardin** [comment] 2022-01-17 11:03
I will close this issue as it is not an issue per se (not a bug, design flaw, workflow critique,...).
In the future, if you have such questions, feel free to start a discussion in the Discussions tab of the repo :)

**Closed by emuskardin** 2022-01-17 11:03 UTC
